apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: {{ .Values.config.appName | quote }}
  MESSAGE: {{ .Values.config.message | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
