apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: beginner-api
  template:
    metadata:
      labels:
        app: beginner-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: postgres-secret
