apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claims-platform
resources:
  - ../../base
  - hpa.yaml
  - pdb.yaml
  - networkpolicy.yaml
patches:
  - path: deployment-patch.yaml
