apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: claims-api
spec:
  podSelector:
    matchLabels:
      app: claims-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
