apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claims-api
spec:
  ingressClassName: nginx
  rules:
    - host: claims.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: claims-api
                port:
                  number: 80
