apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-api
  namespace: beginner-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beginner-api
  template:
    metadata:
      labels:
        app: beginner-api
    spec:
      containers:
        - name: api
          image: beginner-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
