apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claims-platform
resources:
  - ../../base
images:
  - name: claims-api
    newName: ghcr.io/shauritanga/claims-api
    newTag: local
patches:
  - path: deployment-patch.yaml
